jobs:
- job: CIReleaseValidation
  timeoutInMinutes: 90
  pool:
    name: Analog On-Prem
    demands:
    - Unity2018.3.7f1  # variable expansion not allowed here
    - COG-UnityCache-WUS2-01
    - SDK_18362 -equals TRUE
  steps:
  - powershell: |
      git clone -b mrtk $(scriptsRepoURL) $(Build.ArtifactStagingDirectory)\scripts
    displayName: "Clone release scripts"
  - powershell: |
      Get-ChildItem -Path $(Build.ArtifactStagingDirectory)\scripts
    displayName: "List files"
